# run with 
version: '3.8'

services:
  retrieval-app:
    build:
      context: ../../../
      dockerfile: Dockerfile
    image: jon730/chatgpt-retrieval-plugin
    ports:
      - "80:8000"
    depends_on:
      - qdrant
    environment:
      DATASTORE: "qdrant"
      QDRANT_URL: "http://qdrant"
      BEARER_TOKEN: "${BEARER_TOKEN}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
  qdrant:
    image: qdrant/qdrant:v1.0.3
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  qdrant-data: